### ISSUE TITLE
[ENVIRONMENT] 백엔드 환경세팅

### ISSUE THREAD

**Issue by marshot9420** [marshot9420/marsmall#1]
### 🤔 Describe

NestJS & TypeORM & Swagger OpenAPI 환경세팅 필요

### ✅ Tasks

- [x] NestJS 애플리케이션 생성
- [x] Prettier 설정
- [x] 절대경로 import/test 설정
- [x] @nestjs/config + .env 파일 적용
- [x] Swagger OpenAPI 의존성 추가
- [x] TypeORM 추가 & 연결
- [x] CommonEntity 추가: DB 레코드 생성일/수정일 기록용
- [x] CORS 설정
- [x] HttpExceptionFilter 추가
- [x] SucessInterceptor 추가
- [x] cookie-parser 추가
- [x] class-validator 추가
- [x] Winston Logger 추가
