### ISSUE TITLE
[ENVIRONMENT] 프론트엔드 환경세팅

### ISSUE THREAD

**Issue by marshot9420** [marshot9420/marsmall#3]
### 🤔 Describe

프론트엔드 환경세팅 필요

### ✅ Tasks

- [ ] 프론트엔드 모노레포 구축
- [ ] Prettier 설정
- [ ] ESLint 설정
- [ ] Vite 기본 설정
- [ ] TypeScript 설정
- [ ] index.html 및 관련 설정 추가
- [ ] Babel 설정
- [ ] emotion 라이브러리 추가
- [ ] 절대경로 설정
- [ ] React 의존성 추가
- [ ] axios 의존성 추가
- [ ] Global Style 적용
- [ ] @tanstack/react-query 의존성 추가
- [ ] react-icons 의존성 추가
- [ ] 스타일 mixins 추가
- [ ] 환경변수 설정
- [ ] Storybook 설정 추가
